[build]
    functions = "netlify/functions"
    publish = "build"

[[redirects]]
  from = "/api/reddit-sub-icons/:subreddit"
  to = "/.netlify/functions/reddit-sub-icons/:subreddit"
  status = 200


[[redirects]]
  from = "/api/reddit-popular-subreddits"
  to = "/.netlify/functions/reddit-popular-subreddits"
  status = 200